/*
 * CONNECTIONS.h
 *
 * Created: 10/10/2020 2:15:54 PM
 *  Author: ideapad510
 */ 


#ifndef CONNECTIONS_H_
#define CONNECTIONS_H_
#include "microconfigrations.h"
#define CONTROL_DDR PORTB_DDRA_ADDRESS
#define CONTROL_INMOD PORTB_INMOD_ADDRESS
#define CONTROL_IN PORTB_IN_ADDRESS
#define SECBUTTONS 0
#define MINBUTTONS 1
#define HOURBUTTONS 2
#define SETBUTTON   3

#define CAP_BUTTON_OUT_DDR_ADDRESS		PORTB_DDRA_ADDRESS
#define CAP_BUTTON_OUT_OUT_ADDRESS		PORTB_OUT_ADDRESS
#define CAP_BUTTON_OUT_OUTMOD_ADDRESS	PORTB_OUTMOD_ADDRESS
#define CAP_BUTTON_OUT_PIN              4

#define CAP_BUTTON_IN_DDR_ADDRESS		PORTB_DDRA_ADDRESS
#define CAP_BUTTON_IN_IN_ADDRESS		PORTB_IN_ADDRESS
#define CAP_BUTTON_IN_OUT_ADDRESS		PORTB_OUT_ADDRESS
#define CAP_BUTTON_IN_INMOD_ADDRESS		PORTB_INMOD_ADDRESS
#define CAP_BUTTON_IN_PIN               5
/*

#define PORT7SEG_DDR_ADDRESS PORTD_DDRA_ADDRESS
#define PORT7SEG_OUTMOD_ADDRESS PORTD_OUTMOD_ADDRESS
#define PORT7SEG_OUT_ADDRESS PORTD_OUT_ADDRESS

#define PORT7SEGUNITS_DDR_ADDRESS PORTC_DDRA_ADDRESS
#define PORT7SEGUNITS_OUTMOD_ADDRESS PORTC_OUTMOD_ADDRESS
#define PORT7SEGUNITS_OUT_ADDRESS PORTC_OUT_ADDRESS
#define PIN_H1 0
#define PIN_H0 1
#define PIN_M1 2
#define PIN_M0 3
#define PIN_S1 4
#define PIN_S0 5
*/

#endif /* CONNECTIONS_H_ */